# Generated by Django 5.1.4 on 2024-12-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_allprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='fullImage',
            field=models.ImageField(blank=True, null=True, upload_to='projects/photos'),
        ),
    ]
