# Generated by Django 5.1.4 on 2024-12-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_allprojects_fullimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='allprojects',
            name='technology',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
