# Generated by Django 5.1.4 on 2024-12-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_allprojects_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeDescribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(blank=True, null=True, verbose_name=1500)),
            ],
        ),
    ]
