# Generated by Django 5.1.4 on 2024-12-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0005_wholedescribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeWholeDescription',
        ),
    ]
