# Generated by Django 5.1.4 on 2024-12-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinformation',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='phone_number1',
            field=models.CharField(blank=True, help_text='Your phone number 1', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='phone_number2',
            field=models.CharField(blank=True, help_text='Your phone number 2', max_length=15, null=True),
        ),
    ]
