# Generated by Django 5.1.4 on 2024-12-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_remove_socialinformation_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinformation',
            name='email',
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='email1',
            field=models.EmailField(blank=True, help_text='Your email address 2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='email2',
            field=models.EmailField(blank=True, help_text='Your email address 2', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='phone_number3',
            field=models.CharField(blank=True, help_text='Your phone number 2', max_length=15, null=True),
        ),
    ]
