# Generated by Django 5.1.4 on 2024-12-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_remove_socialinformation_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinformation',
            name='phone_number2',
            field=models.CharField(blank=True, help_text='Your phone number 2', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='socialinformation',
            name='phone_number3',
            field=models.CharField(blank=True, help_text='Your phone number 2', max_length=25, null=True),
        ),
    ]
