# Generated by Django 5.1.4 on 2024-12-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0004_alter_socialinformation_phone_number2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinformation',
            name='phone_number1',
            field=models.CharField(blank=True, help_text='Your phone number 1', max_length=25, null=True),
        ),
    ]
