# Generated by Django 5.1.4 on 2025-02-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0007_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialinformation',
            name='phone_number1',
        ),
        migrations.RemoveField(
            model_name='socialinformation',
            name='phone_number2',
        ),
        migrations.RemoveField(
            model_name='socialinformation',
            name='phone_number3',
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Your phone number ', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='skype',
            field=models.CharField(blank=True, help_text='Your Skype', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='socialinformation',
            name='whatsApNumber',
            field=models.CharField(blank=True, help_text='Your whatsApp number', max_length=25, null=True),
        ),
    ]
