# Generated by Django 5.1.4 on 2024-12-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0004_aboutmodel_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skillName', models.CharField(blank=True, max_length=100, null=True)),
                ('skillLogo', models.ImageField(blank=True, null=True, upload_to='logo/photos')),
            ],
        ),
        migrations.AddField(
            model_name='skillsmodel',
            name='skillLogo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/photos'),
        ),
    ]
