# Generated by Django 5.1.4 on 2025-01-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0006_familiarmodel_hostingmodel_othersmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
