# Generated by Django 5.1.4 on 2025-02-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0007_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmodel',
            name='background_mobile_img',
            field=models.ImageField(blank=True, null=True, upload_to='background/photos'),
        ),
    ]
