# Generated by Django 5.1.4 on 2025-02-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('About', '0008_aboutmodel_background_mobile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='background_mobile_img',
        ),
    ]
