# Generated by Django 5.1.4 on 2024-12-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of the job position (e.g., Software Engineer).', max_length=300, null=True, verbose_name='Job Title')),
                ('expDescription', models.TextField(blank=True, help_text='A brief description of whole experience.', max_length=100, null=True, verbose_name='Whole Experience Summery')),
                ('company', models.CharField(blank=True, help_text='The name of the company where you worked.', max_length=300, null=True, verbose_name='Company Name')),
                ('summary', models.TextField(blank=True, help_text='A brief description of your role and responsibilities.', max_length=1000, null=True, verbose_name='Experience Summary')),
                ('start_date', models.DateField(help_text='The date when you started this job.', verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, help_text='The date when you left this job. Leave blank if currently working.', null=True, verbose_name='End Date')),
                ('is_current', models.BooleanField(default=False, help_text='Check if you are currently working in this position.', verbose_name='Currently Working')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['-start_date'],
            },
        ),
    ]
