# Generated by Django 5.1.4 on 2024-12-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='expDescription',
            field=models.TextField(blank=True, help_text='A brief description of whole experience.', max_length=5000, null=True, verbose_name='Whole Experience Summery'),
        ),
    ]
