# Generated by Django 5.1.4 on 2024-12-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0003_education'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-start_date']},
        ),
    ]
